name: react to dispatch event

on: 
  repository_dispatch:
    types: [ custom_event_type ]
  
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make changes
        run: date +%s > report.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.PAT_TOKEN}}
          commit-message: "chore: auto pr"
          title: "Auto PR Test"
        