name: merge approved pr

on:
  workflow_run:
    workflows: [PR Approval Dispatcher]
    types: 
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/github-script@v6
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
          });
          console.log('all', allArtifacts);
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "context"
          })[0];
          console.log('matchArtifact', matchArtifact);
          let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/context.zip`, Buffer.from(download.data));

    - name: Unzip artifact
      run: unzip context.zip

    - name: Checkout
      uses: actions/checkout@v3

    - name: Check file
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          const fs = require('fs');
          const contextStr = fs.readFileSync('./context');
          const contextObject = JSON.parse(contextStr);
          const prContext = await github.request(contextObject.payload.pull_request.url);
          console.log(contextObject.payload.pull_request.url, prContext, prContext.data.head.label);
          await exec.exec(`git fetch -fu origin refs/pull/${prContext.number}/head:sw-pub-pr-${prContext.number}`);
          github.rest.repos.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: 'main',
            head: `sw-pub-pr-${prContext.number}`
          });
            