name: merge approved pr

on:
  workflow_run:
    workflows: [PR Approval Dispatcher]
    types: 
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/github-script@v6
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "context"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

    - name: Unzip artifact
      run: unzip pr_number.zip

    - name: Check file
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          let fs = require('fs');
          let info = Number(fs.readFileSync('./context'));
          console.log(info);
            