name: PR Approval Dispatcher

on:
  pull_request_review:
    types: [submitted]

jobs:
  transfer:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Save Context
      uses: actions/github-script@v6
      with: 
        script: |
          const fs = require('fs');
          fs.mkdir('./pr');
          fs.writeFileSync('./pr/context', JSON.stringify(context));
    - uses: actions/upload-artifact@v2
        with:
          name: context
          path: pr/