name: PR Approval Dispatcher

on:
  pull_request_review:
    types: [submitted]

jobs:
  transfer:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Save Context
      uses: actions/github-script@v6
      with: 
        script: |
          const hasDocLabel = context.payload.pull_request.labels.some(label => label.name === 'documentation');
          const doesApprovalCount = ['OWNER', 'CONTRIBUTOR'].includes(context.payload.review.author_association);
          console.log(hasDocLabel, doesApprovalCount);
          console.log(context.payload.pull_request);
